### ISSUE TITLE
Not able to pass two different groups name using lambda function. 

### ISSUE THREAD

**Issue by megha4thcloud** [awslabs/ssosync#98] opened 2022-09-14 10:17 UTC
I want to add two groups from GSUIT to AWS SSO. abc@example.com and cdf@example.com but not sure how to pass it? 

In GoogleGroupMatch I am trying to give email:abc*,email:cdf* but not getting anything in debugging log also not creating any user. Please help me How to pas two different groups?

**Comment by bmb5** [comment] 2022-10-14 17:49
+1

**Comment by treylon** [comment] 2022-12-27 10:16
@megha4thcloud I ran into the same issue - it seems that Google only supports `AND` as an operator when specifying multiple clauses. https://developers.google.com/admin-sdk/directory/v1/guides/search-groups

Is it planned to allow multiple clauses manually throw implementing it on ssosync side?

**Comment by ChrisPates** [comment] 2023-01-20 17:58
Working on this feature in the linked branch.

**Comment by ChrisPates** [comment] 2023-01-24 18:54
Duplicate of [How to format multiple groups under groupmatch](https://github.com/awslabs/ssosync/issues/69#top)](https://github.com/awslabs/ssosync/issues/69)

**Closed by ChrisPates** 2023-01-24 18:54 UTC
Labels: enhancement
