### ISSUE TITLE
Nested google groups are not synchronised correctly in AWS 

### ISSUE THREAD

**Issue by alexku7** [awslabs/ssosync#51] opened 2021-06-08 17:17 UTC
We have nested groups in google . For example group A contains group B . The group B has a user Y.

In this scenario, In thew AWS SSO we expect to see  that the group A will have the Group B inside or the user Y directly.

Seems AWS SSO doesn"t support nested groups and the ssosync script doesn"t expand nested group recursively

**Comment by icj217** [comment] 2021-06-24 19:18
This seems related to/a duplicate of https://github.com/awslabs/ssosync/issues/27

**Comment by ChrisPates** [comment] 2023-01-24 18:52
duplicate of [https://github.com/awslabs/ssosync/issues/66](https://github.com/awslabs/ssosync/issues/66)

**Closed by ChrisPates** 2023-01-24 18:52 UTC
